// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  productsSidebar: [{ type: 'autogenerated', dirName: 'products' }],
  ecDesignerSidebar: [{ type: 'autogenerated', dirName: 'ec-designer' }],
  ecStoreSidebar: [{ type: 'autogenerated', dirName: 'ec-store' }],
  ecDropshipSidebar: [{ type: 'autogenerated', dirName: 'ec-dropship' }],
  ecFactorySidebar: [{ type: 'autogenerated', dirName: 'ec-factory' }],
  ecCrmSidebar: [{ type: 'autogenerated', dirName: 'ec-crm' }],
};

export default sidebars;

