backend:
  name: github
  repo: amit4184/ezyresource
  branch: main

media_folder: "static/img"
public_folder: "/img/"

collections:
  # ---------- ENGLISH ----------
  - name: tutorial
    label: "Tutorial"
    folder: docs/tutorial-basics
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: slug, label: Slug, widget: string }
      - { name: tags, label: Tags, widget: list }
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: imageUrl, label: ImageURL, widget: string }

  - name: products
    label: "Products"
    folder: docs/products
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-designer
    label: "EC Designer"
    folder: docs/ec-designer
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-store
    label: "EC Store"
    folder: docs/ec-store
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-dropship
    label: "EC Dropship"
    folder: docs/ec-dropship
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-factory
    label: "EC Factory"
    folder: docs/ec-factory
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-crm
    label: "EC CRM"
    folder: docs/ec-crm
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  # ---------- JAPANESE ----------
  - name: tutorial-ja
    label: "Tutorial (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: products-ja
    label: "Products (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-products/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-designer-ja
    label: "EC Designer (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-designer/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-store-ja
    label: "EC Store (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-store/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-dropship-ja
    label: "EC Dropship (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-dropship/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-factory-ja
    label: "EC Factory (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-factory/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-crm-ja
    label: "EC CRM (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-crm/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }
