backend:
  name: github
  repo: amit4184/ezyresource
  branch: main

media_folder: "static/img"
public_folder: "/img/"

collections:
  # ---------- HOMEPAGE TRANSLATIONS ----------
  - name: homepage-translations
    label: "Homepage Translations"
    files:
      - label: "English Homepage"
        name: "homepage-en"
        file: "i18n/en/code.json"
        fields:
          - { name: "homepage.title.message", label: "Page Title", widget: string }
          - { name: "homepage.subtitle.message", label: "Page Subtitle", widget: text }
          - { name: "homepage.getStarted.title.message", label: "Get Started Title", widget: string }
          - { name: "homepage.getStarted.description.message", label: "Get Started Description", widget: text }
          - { name: "homepage.photobookDesigner.title.message", label: "Photobook Designer Title", widget: string }
          - { name: "homepage.photobookDesigner.description.message", label: "Photobook Designer Description", widget: text }
          - { name: "homepage.printDesigner.title.message", label: "Print Designer Title", widget: string }
          - { name: "homepage.printDesigner.description.message", label: "Print Designer Description", widget: text }
          - { name: "homepage.calendarDesigner.title.message", label: "Calendar Designer Title", widget: string }
          - { name: "homepage.calendarDesigner.description.message", label: "Calendar Designer Description", widget: text }
          - { name: "homepage.customProductDesigner.title.message", label: "Custom Product Designer Title", widget: string }
          - { name: "homepage.customProductDesigner.description.message", label: "Custom Product Designer Description", widget: text }
          - { name: "homepage.dtfProductDesigner.title.message", label: "DTF Product Designer Title", widget: string }
          - { name: "homepage.dtfProductDesigner.description.message", label: "DTF Product Designer Description", widget: text }
          - { name: "homepage.learnMore.message", label: "Learn More Text", widget: string }
      
      - label: "Japanese Homepage"
        name: "homepage-ja"
        file: "i18n/ja/code.json"
        fields:
          - { name: "homepage.title.message", label: "ページタイトル", widget: string }
          - { name: "homepage.subtitle.message", label: "ページサブタイトル", widget: text }
          - { name: "homepage.getStarted.title.message", label: "はじめにタイトル", widget: string }
          - { name: "homepage.getStarted.description.message", label: "はじめに説明", widget: text }
          - { name: "homepage.photobookDesigner.title.message", label: "フォトブックデザイナータイトル", widget: string }
          - { name: "homepage.photobookDesigner.description.message", label: "フォトブックデザイナー説明", widget: text }
          - { name: "homepage.printDesigner.title.message", label: "印刷デザイナータイトル", widget: string }
          - { name: "homepage.printDesigner.description.message", label: "印刷デザイナー説明", widget: text }
          - { name: "homepage.calendarDesigner.title.message", label: "カレンダーデザイナータイトル", widget: string }
          - { name: "homepage.calendarDesigner.description.message", label: "カレンダーデザイナー説明", widget: text }
          - { name: "homepage.customProductDesigner.title.message", label: "カスタム製品デザイナータイトル", widget: string }
          - { name: "homepage.customProductDesigner.description.message", label: "カスタム製品デザイナー説明", widget: text }
          - { name: "homepage.dtfProductDesigner.title.message", label: "DTF製品デザイナータイトル", widget: string }
          - { name: "homepage.dtfProductDesigner.description.message", label: "DTF製品デザイナー説明", widget: text }
          - { name: "homepage.learnMore.message", label: "詳細リンクテキスト", widget: string }

  # ---------- ENGLISH COLLECTIONS ----------
  - name: tutorial
    label: "Tutorial"
    folder: docs/tutorial-basics
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: slug, label: Slug, widget: string, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - label: "Authors"
        name: "authors"
        widget: "list"
        required: false
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: imageUrl, label: ImageURL, widget: string }

  - name: products
    label: "Products"
    folder: docs/products
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-designer
    label: "EC Designer"
    folder: docs/ec-designer
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-store
    label: "EC Store"
    folder: docs/ec-store
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-dropship
    label: "EC Dropship"
    folder: docs/ec-dropship
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-factory
    label: "EC Factory"
    folder: docs/ec-factory
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: ec-crm
    label: "EC CRM"
    folder: docs/ec-crm
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: "Sidebar Label", widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  # ---------- JAPANESE COLLECTIONS ----------
  - name: tutorial-ja
    label: "Tutorial (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: products-ja
    label: "Products (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-products/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-designer-ja
    label: "EC Designer (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-designer/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-store-ja
    label: "EC Store (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-store/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-dropship-ja
    label: "EC Dropship (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-dropship/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-factory-ja
    label: "EC Factory (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-factory/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }

  - name: ec-crm-ja
    label: "EC CRM (日本語)"
    folder: i18n/ja/docusaurus-plugin-content-docs-ec-crm/current
    create: true
    slug: "{{slug}}"
    nested: { depth: 10 }
    fields:
      - { name: title, label: "タイトル", widget: string }
      - { name: sidebar_label, label: "サイドバーラベル", widget: string, required: false }
      - { name: body, label: "本文", widget: markdown }
